language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.2

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source --no-interaction --dev

script:
  - phpunit --configuration tests/phpunit.xml